### ISSUE TITLE
add support for Route and Ingress resources

### ISSUE THREAD

**Issue by adisos** [np-guard/netpol-analyzer#112]
`connlist` command should consider connectivity inferred from `Route` and `Ingress` resources as well, combined with network policy connectivity analysis.
For example, consider the Route below:
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world
  namespace: helloworld
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: hello-world
    weight: 100
```

The report of `connlist` may contain a line as follows:
`{ingress-controller} => hello-world : TCP 8080` 

But, if network policy analysis identifies that such connectivity is not permitted, this line will not be added to the report.
