### ISSUE TITLE
update `dependabot.yaml`

### ISSUE THREAD

**Issue by adisos** [np-guard/netpol-analyzer#596]
please update as follows:
```
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
```
